---
host: 0.0.0.0
title: Stanford Christian Students
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  media:
    output: true
    sort_by: index
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    _options:
      content:
        width: 1880
        height: 1880
        uploads_dir: "/images/posts/"
- scope:
    path: ''
  values:
    layout: default
url: http://web.stanford.edu/group/christianstudent/
google_analytics_key: 
logo: http://web.stanford.edu/group/christianstudent/images/logo.svg
description: Website for Stanford Christian Students
author:
  name: 
  email: 
  twitter: 
social:
  name: stanfordchristianstudents
  links:
  - https://www.instagram.com/stanfordchristianstudents/
  - https://www.facebook.com/stanfordchristianstudents/
permalink: pretty
future: true
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
- vendor
_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
paginate: 6
paginate_path: "blog/page:num/"
