---
host: 0.0.0.0
title: Stanford Christian Students
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  media:
    output: true
    sort_by: index
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    _options:
      content:
        width: 1880
        height: 1880
        uploads_dir: "/images/posts/"
- scope:
    path: ''
  values:
    layout: default
url: http://web.stanford.edu/group/christianstudent/
google_analytics_key: 
logo: http://web.stanford.edu/group/christianstudent/images/logo.svg
description: A Website for the Stanford Christian Students club
tagline: Stanford Christian Students
author:
  name: 
  email: 
  twitter: 
social:
  name: stanfordchristianstudents
  links:
    instagram: https://www.instagram.com/stanfordchristianstudents/
    facebook: https://www.facebook.com/stanfordchristianstudents/
    youtube: https://youtube.com/playlist?list=PLPSD9A5bdIk0iLnQCznD7cMS6SpqxAIg-&feature=shared
permalink: pretty
future: true
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
- jekyll/webpack
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- vendor
- package.json
- package-lock.json
- tsconfig.json
- node_modules
_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
paginate: 6
paginate_path: "blog/page:num/"
